### PR TITLE
Only time sync for live content

### PR DESCRIPTION
**Pull request by LloydW93**

### CODE REVIEW

**Comment by LloydW93** [comment]
18:08:38    davide  that's not strictly correct
18:08:56    davide  you can have an availabilityStartTime in a static mpd
18:09:07    davide  in that case you would want to time sync

**Comment by JibberJim** [comment]
If we do want to time-sync, we don't want to use time.akamai anyway, we have our own sources to use.

**Comment by LloydW93** [comment]
Yes, but this change still wouldn't attempt for static with an AST

**Comment by LloydW93** [comment]
I'm going to merge this as-is for now, but we should remember to come back to this if we ever merge this change upstream.

**Comment by LloydW93** [comment]
Also needs 8f598bd/2e2c34f

**Pull request merged**
